# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Orchestrate or schedule a set of jobs
jobs:
  creating_infrastructure:
    docker:
      - image: ami-055901a576342a263
    steps:
      - aws-cli/install
      - aws-cli/configure :
          aws-access-key-id: $AWS_ACCESS_KEY_ID
          aws-region: $AWS_DEFAULT_REGION
          aws-secret-access-key: $AWS_SECRET_ACCESS_KEY
          profile-name: default
      - checkout
      - create-stack:
          branch:  master
          git-url: https://github.com/elmazon/Creating_Infrastructure.git
          stack-name: "CDstack"  
          template-file-path: ~/Git/Creating_Infrastructure/template.yml
workflows:
  # Name the workflow "welcome"
  creating_infr:
    jobs:
      - creating_infrastructure:
          context: AWS
